server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pharmacy_db
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: TXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTA=
  expiration: 86400000