server:
  port: 8082

spring:
  application:
    name: medicine-service

  datasource:
    url: jdbc:mysql://localhost:3307/pharma_medicine_db
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: TXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTA=
  expiration: 86400000